[toolchain]
anchor_version = "0.30.0"
solana_version = "1.17.13"

[features]
seeds = false
skip-lint = false

[programs.localnet]
program_playground = "5qycotNGxEobw7EajCcwsomXTx4fYjFXwvRnExpvcFc9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/daiwanwei/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
